#!/bin/bash

clear
  printf "\033[0;36m♡⃛◟( ˊ̱˂˃ˋ̱ )◞⸜₍ ˍ́˱˲ˍ̀ ₎⸝◟( ˊ̱˂˃ˋ̱ )◞♡⃛\033[0m\n"
  printf "\033[0;36m===========================\033[0m\n"
  printf "\033[34;1mWelcome!!!\033[0m\n"
  printf "\033[34;1mAuto-Reconnect Menu\033[0m\n"
  printf "\033[0;36m===========================\033[0m\n"
  printf "\033[34;1mStale | PHCorner.net\033[0m\n"
  printf "\033[0;36m===========================\033[0m\n"
  printf "\033[0;36m♪＼(*＾▽＾*)／＼(*＾▽＾*)／\033[0m\n"
  echo ""
  printf "\033[34;1mWhat do you want to do?\033[0m\n"
  echo ""
  printf "\033[0;35m1) Configure autorecon for your dropbear port.\033[0m\n"
  echo "2) Change Autorecon Interval."
  printf "\033[0;35m0) Exit\033[0m\n"
  echo ""
  echo ""
  echo -e "Enter your response \c"
  read -r answer
  case "$answer" in
    1) clear
       echo "===================="
       echo "===DROPBEAR PORTS==="
       echo "===================="
       echo ""
       echo "What is your current Dropbear port?"
       echo ""
       echo -e "Enter your dropbear port or x to exit \c"
       read -r n
       case $n in
         $n) cp /root/stale/.baseport /root/stale/.kill.sh
             sed -i "s/base/$n/g" /root/stale/.kill.sh
             echo "Autorecon is successfully configured on dropbear port $n";;
          x) exit;;
       esac ;;
    2) clear
       echo "===================="
       echo "AUTO-RECONNECT TIMER"
       echo "===================="
       echo ""
       echo "How many seconds before reconnection?"
       echo ""
       echo ""
       echo -e "Enter your preferred interval(1-60) or x to exit \c"
       read -r n
       case $n in
         $n) cp /root/stale/.basetime /root/stale/.sleep.sh
             sed -i "s/base/$n/g" /root/stale/.sleep.sh
             echo "Autorecon is now every $n seconds.";;
          x) exit;;
       esac ;;
    0) exit ;;
  esac
